development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

test:
  adapter: postgresql
  encoding: utf8
  # database: inventory_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  # database: inventory_production
  pool: 5
  timeout: 5000
